version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: developerstore_postgres
    restart: always
    environment:
      POSTGRES_USER: devstore
      POSTGRES_PASSWORD: devstore123
      POSTGRES_DB: DeveloperStoreDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: developerstore_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
